# Form implementation generated from reading ui file 'banve.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 825)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(69, 79, 871, 141))
        self.groupBox.setObjectName("groupBox")
        self.name = QtWidgets.QLineEdit(parent=self.groupBox)
        self.name.setGeometry(QtCore.QRect(160, 30, 251, 22))
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(70, 100, 55, 16))
        self.label_3.setObjectName("label_3")
        self.sex = QtWidgets.QComboBox(parent=self.groupBox)
        self.sex.setGeometry(QtCore.QRect(160, 100, 73, 22))
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 220, 871, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.coffee = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.coffee.setGeometry(QtCore.QRect(10, 30, 81, 20))
        self.coffee.setObjectName("coffee")
        self.food = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.food.setGeometry(QtCore.QRect(110, 30, 81, 20))
        self.food.setObjectName("food")
        self.person = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.person.setGeometry(QtCore.QRect(110, 80, 42, 22))
        self.person.setObjectName("person")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 61, 21))
        self.label_4.setObjectName("label_4")
        self.child = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.child.setGeometry(QtCore.QRect(110, 140, 42, 22))
        self.child.setObjectName("child")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 61, 21))
        self.label_5.setObjectName("label_5")
        self.bill = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bill.setGeometry(QtCore.QRect(130, 410, 93, 28))
        self.bill.setObjectName("bill")
        self.textBill = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.textBill.setGeometry(QtCore.QRect(290, 410, 191, 31))
        self.textBill.setObjectName("textBill")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 420, 55, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.bill.clicked.connect(self.calcBill)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ỨNG DỤNG BÁN VÉ"))
        self.groupBox.setTitle(_translate("MainWindow", "THÔNG TIN KHÁCH HÀNG"))
        self.label_2.setText(_translate("MainWindow", "Họ và tên"))
        self.label_3.setText(_translate("MainWindow", "Giới tính"))
        self.sex.setItemText(0, _translate("MainWindow", "Nam"))
        self.sex.setItemText(1, _translate("MainWindow", "Nữ"))
        self.groupBox_2.setTitle(_translate("MainWindow", "DỊCH VỤ"))
        self.coffee.setText(_translate("MainWindow", "Coffee"))
        self.food.setText(_translate("MainWindow", "Food"))
        self.label_4.setText(_translate("MainWindow", "Người lớn"))
        self.label_5.setText(_translate("MainWindow", "Trẻ em"))
        self.bill.setText(_translate("MainWindow", "TÍNH TIỀN"))
        self.label_6.setText(_translate("MainWindow", "VND"))

    def calcBill(self):
        sumBill = 0
        price = {
            "coffee": 100000,
            "food": 50000,
            "person": 200000,
            "child": 100000
        }
        cf_price = 0
        if self.coffee.checkState()!=0:
            cf_price = price["coffee"]
        food_price = 0
        if self.coffee.checkState()!=0:
            food_price = price["food"] 
        person_price = int(self.person.text())*price["person"]
        child_price = int(self.child.text())*price["child"]
        sumBill = cf_price + food_price + person_price + child_price

        self.textBill.setText(str(sumBill))

        msg = QtWidgets.QMessageBox()
        msg.setInformativeText(str(sumBill)+" VND")
        msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
