# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2

from PyQt6 import QtCore, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1062, 829)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uploadBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.uploadBtn.setGeometry(QtCore.QRect(10, 720, 93, 31))
        self.uploadBtn.setObjectName("uploadBtn")
        self.invertedBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.invertedBtn.setGeometry(QtCore.QRect(550, 160, 111, 31))
        self.invertedBtn.setObjectName("invertedBtn")
        self.imageScreen = QtWidgets.QLabel(parent=self.centralwidget)
        self.imageScreen.setGeometry(QtCore.QRect(10, 30, 511, 681))
        self.imageScreen.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.imageScreen.setLineWidth(3)
        self.imageScreen.setMidLineWidth(3)
        self.imageScreen.setText("")
        self.imageScreen.setScaledContents(True)
        self.imageScreen.setObjectName("imageScreen")
        self.imgProcess = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgProcess.setGeometry(QtCore.QRect(690, 30, 511, 681))
        self.imgProcess.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.imgProcess.setLineWidth(3)
        self.imgProcess.setMidLineWidth(3)
        self.imgProcess.setText("")
        self.imgProcess.setScaledContents(True)
        self.imgProcess.setObjectName("imgProcess")
        self.dirText = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.dirText.setGeometry(QtCore.QRect(120, 720, 350, 30))
        self.dirText.setObjectName("dirText")
        self.binariBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.binariBtn.setGeometry(QtCore.QRect(550, 210, 111, 31))
        self.binariBtn.setObjectName("binariBtn")
        self.noiseBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.noiseBtn.setGeometry(QtCore.QRect(550, 260, 111, 31))
        self.noiseBtn.setObjectName("noiseBtn")
        self.thinBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.thinBtn.setGeometry(QtCore.QRect(550, 310, 111, 31))
        self.thinBtn.setObjectName("thinBtn")
        self.thickBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.thickBtn.setGeometry(QtCore.QRect(550, 360, 111, 31))
        self.thickBtn.setObjectName("thickBtn")
        self.thickBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.thickBtn_2.setGeometry(QtCore.QRect(550, 410, 111, 31))
        self.thickBtn_2.setObjectName("thickBtn_2")
        self.borderBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.borderBtn.setGeometry(QtCore.QRect(550, 460, 111, 31))
        self.borderBtn.setObjectName("borderBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.uploadBtn.clicked.connect(self.upload_img)
        self.invertedBtn.clicked.connect(self.inverted_img)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uploadBtn.setText(_translate("MainWindow", "Upload"))
        self.invertedBtn.setText(_translate("MainWindow", "Inverted"))
        self.binariBtn.setText(_translate("MainWindow", "Binarization"))
        self.noiseBtn.setText(_translate("MainWindow", "Remove Noise"))
        self.thinBtn.setText(_translate("MainWindow", "Thin"))
        self.thickBtn.setText(_translate("MainWindow", "Thick"))
        self.thickBtn_2.setText(_translate("MainWindow", "Rotate"))
        self.borderBtn.setText(_translate("MainWindow", "Remove Border"))
    
    def upload_img(self):
        link_path = QFileDialog.getOpenFileName(filter="*.jpg *.png")
        self.imageScreen.setPixmap(QPixmap(link_path[0]))
        self.dirText.setText(link_path[0])

        return link_path
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
